apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.environment }}-redis-slave
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v3
        resources:
          requests:
            cpu: {{ pluck .Values.environment .Values.cpu | first | default .Values.cpu._default }}
            memory: {{ pluck .Values.environment .Values.memory | first | default .Values.memory._default }}
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 6379
